[module]
[module.hugoVersion]
extended = true
min = '0.90.0'

[params]
customCSS = ["css/terminal.css"]
centerTheme = true
autoCover = false
showLastUpdated = false
updatedDatePrefix = "@"

languageName = "English"
title = "jopen"

subtitle = "To Learn In Public."
owner = "jfryusef"
keywords = ""
copyright = "CC0-1.0"
menuMore = "Show more"
readMore = "Read →"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "This is not the webpage you're looking for."
missingBackButtonLabel = "Homepage"
minuteReadingTime = "minutes"
words = "words"

[params.logo]
logoText = "jopen"
logoHomeLink = "/"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "https://www.google.com/search?q=site%3Ajfryusef.link+QUERY"
weight = 30
